"""
Thompson's Construction (NFA Builder)
=====================================
Owned by: Member A (Automata Theory Engine)

Module Overview:
----------------
This module implements Thompson's Construction algorithm. It walks the
Regex AST generated by `regex_parser` and recursively builds an equivalent
Non-Deterministic Finite Automaton with epsilon (ε) transitions.

Key Invariants in Thompson's Construction:
------------------------------------------
1. Exactly one initial (start) state.
2. Exactly one final (accepting) state.
3. Every basic transition is either on a single character or ε.
4. Composite constructions:
   - Concatenation: Connect final state of NFA1 to start state of NFA2 via ε.
   - Alternation (|): Fork new start state into start(NFA1) and start(NFA2) via ε;
     connect accept(NFA1) and accept(NFA2) to new accept state via ε.
   - Kleene Star (*): Add loopback from accept(NFA) to start(NFA) via ε,
     and bypass from new start to new accept via ε.

Expected Input:
---------------
  ast: RegexNode (from regex_parser)

Expected Output:
----------------
  Automaton (type="NFA", serialized conforming to docs/json_schema.md)
"""

from typing import Optional
from ..models import Automaton, State, Transition
from ..regex_parser.parser import RegexNode


class NFABuilder:
    """
    Builder responsible for generating NFAs from Regex ASTs via Thompson's algorithm.

    TODO (Member A):
      1. Implement sub-builders for each RegexNodeType (LITERAL, EPSILON, CONCAT, UNION, STAR).
      2. Manage unique state naming (e.g., s0, s1, s2, ...).
      3. Maintain epsilon transitions marked with symbol="ε" or "".
      4. Export output into canonical `Automaton` model.
    """

    def __init__(self):
        self._state_counter = 0

    def _new_state_id(self) -> str:
        """Generates a fresh unique state identifier."""
        sid = f"s{self._state_counter}"
        self._state_counter += 1
        return sid

    def build_from_ast(self, ast: RegexNode, regex_str: Optional[str] = None) -> Automaton:
        """
        Recursively translates a Regex AST into an NFA.

        Args:
            ast (RegexNode): Root node of the parsed regular expression AST.
            regex_str (Optional[str]): Original regex string for metadata.

        Returns:
            Automaton: An NFA conforming to the schema in docs/json_schema.md.

        Raises:
            NotImplementedError: Until Member A implements Thompson's construction.
        """
        # --- PLACEHOLDER FOR MEMBER A ---
        # Implementation roadmap:
        # 1. Base case: LITERAL(c) -> (start) --c--> (accept)
        # 2. Binary UNION: fork and join with epsilon transitions
        # 3. Binary CONCAT: connect left accept to right start with epsilon
        # 4. Unary STAR: loopback and bypass with epsilon transitions
        raise NotImplementedError(
            "NFABuilder.build_from_ast() is assigned to Member A. "
            "Please implement Thompson's Construction algorithm."
        )
