"""
Thompson's Construction (NFA Builder)
=====================================
Owned by: Member A (Automata Theory Engine)

This module implements Thompson's Construction algorithm. It walks the
Regex AST generated by `regex_parser` and recursively builds an equivalent
Non-Deterministic Finite Automaton with epsilon (ε) transitions.

Key Invariants in Thompson's Construction:
------------------------------------------
1. Exactly one initial (start) state and one final (accepting) state per fragment.
2. States are named q0, q1, ... in deterministic order.
3. Every basic transition is either on a single character or ε.
4. Composite constructions:
   - Concatenation: Connect final state of NFA1 to start state of NFA2 via ε.
   - Alternation (|): Fork new start state into start(NFA1) and start(NFA2) via ε;
     connect accept(NFA1) and accept(NFA2) to new accept state via ε.
   - Kleene Star (*): Add loopback from accept(NFA) to start(NFA) via ε,
     and bypass from new start to new accept via ε.
   - Plus (+): Loopback from accept(NFA) to start(NFA) via ε, no empty bypass.
   - Question (?): Fork new start into start(NFA) and new accept via ε,
     connect accept(NFA) to new accept via ε.
"""

from typing import Optional, List, Set, Tuple
import uuid
from dataclasses import dataclass

from ..models import Automaton, State, Transition, AutomatonMetadata
from ..regex_parser.parser import RegexNode, RegexNodeType


@dataclass
class _NFAFragment:
    """Internal container for an NFA fragment with a single start and accept state."""
    start_state: str
    accept_state: str


class NFABuilder:
    """
    Builder responsible for generating NFAs from Regex ASTs via Thompson's algorithm.
    """

    def __init__(self):
        self._state_counter: int = 0
        self._transitions: List[Tuple[str, str, str]] = []
        self._alphabet: Set[str] = set()

    def _new_state_id(self) -> str:
        """Generates a fresh unique state identifier deterministically (q0, q1, ...)."""
        sid = f"q{self._state_counter}"
        self._state_counter += 1
        return sid

    def _add_transition(self, from_state: str, to_state: str, symbol: str) -> None:
        """Records a directed transition."""
        self._transitions.append((from_state, to_state, symbol))
        if symbol != "ε" and symbol != "":
            self._alphabet.add(symbol)

    def build_from_ast(self, ast: RegexNode, regex_str: Optional[str] = None) -> Automaton:
        """
        Recursively translates a Regex AST into an NFA.

        Args:
            ast (RegexNode): Root node of the parsed regular expression AST.
            regex_str (Optional[str]): Original regex string for metadata.

        Returns:
            Automaton: An NFA conforming to the schema in docs/json_schema.md.
        """
        if ast is None:
            raise ValueError("Cannot build NFA from empty AST.")

        # Reset builder state
        self._state_counter = 0
        self._transitions = []
        self._alphabet = set()

        root_fragment = self._build_fragment(ast)

        # Build State objects in deterministic index order
        states: List[State] = []
        for i in range(self._state_counter):
            sid = f"q{i}"
            states.append(
                State(
                    id=sid,
                    label=sid,
                    is_start=(sid == root_fragment.start_state),
                    is_accepting=(sid == root_fragment.accept_state),
                    metadata={},
                )
            )

        # Sort transitions deterministically by (from_state_idx, symbol, to_state_idx)
        def _trans_sort_key(t: Tuple[str, str, str]):
            from_idx = int(t[0][1:]) if t[0].startswith("q") and t[0][1:].isdigit() else t[0]
            to_idx = int(t[1][1:]) if t[1].startswith("q") and t[1][1:].isdigit() else t[1]
            return (from_idx, t[2], to_idx)

        sorted_raw_transitions = sorted(self._transitions, key=_trans_sort_key)

        transitions: List[Transition] = [
            Transition(
                id=f"nt{idx}",
                from_state=u,
                to_state=v,
                symbol=sym,
            )
            for idx, (u, v, sym) in enumerate(sorted_raw_transitions)
        ]

        sorted_alphabet = sorted(list(self._alphabet))
        pattern_str = regex_str or ""

        metadata = AutomatonMetadata(
            regex=pattern_str,
            state_count=len(states),
            transition_count=len(transitions),
            is_minimized=False,
            description="Constructed using Thompson's Algorithm",
        )

        return Automaton(
            id=f"nfa_{uuid.uuid4().hex[:8]}",
            name=f"NFA for {pattern_str}" if pattern_str else "NFA",
            type="NFA",
            alphabet=sorted_alphabet,
            start_state=root_fragment.start_state,
            states=states,
            transitions=transitions,
            metadata=metadata,
        )

    def _build_fragment(self, node: RegexNode) -> _NFAFragment:
        """Recursively builds NFA fragments for AST nodes."""
        if node.type == RegexNodeType.LITERAL:
            start = self._new_state_id()
            accept = self._new_state_id()
            self._add_transition(start, accept, node.value if node.value is not None else "")
            return _NFAFragment(start, accept)

        if node.type == RegexNodeType.EPSILON:
            start = self._new_state_id()
            accept = self._new_state_id()
            self._add_transition(start, accept, "ε")
            return _NFAFragment(start, accept)

        if node.type == RegexNodeType.CONCAT:
            frag1 = self._build_fragment(node.left)
            frag2 = self._build_fragment(node.right)
            # Connect frag1 accept to frag2 start via epsilon
            self._add_transition(frag1.accept_state, frag2.start_state, "ε")
            return _NFAFragment(frag1.start_state, frag2.accept_state)

        if node.type == RegexNodeType.UNION:
            start = self._new_state_id()
            frag1 = self._build_fragment(node.left)
            frag2 = self._build_fragment(node.right)
            accept = self._new_state_id()

            self._add_transition(start, frag1.start_state, "ε")
            self._add_transition(start, frag2.start_state, "ε")
            self._add_transition(frag1.accept_state, accept, "ε")
            self._add_transition(frag2.accept_state, accept, "ε")
            return _NFAFragment(start, accept)

        if node.type == RegexNodeType.STAR:
            start = self._new_state_id()
            child_frag = self._build_fragment(node.child)
            accept = self._new_state_id()

            self._add_transition(start, child_frag.start_state, "ε")
            self._add_transition(start, accept, "ε")
            self._add_transition(child_frag.accept_state, child_frag.start_state, "ε")
            self._add_transition(child_frag.accept_state, accept, "ε")
            return _NFAFragment(start, accept)

        if node.type == RegexNodeType.PLUS:
            start = self._new_state_id()
            child_frag = self._build_fragment(node.child)
            accept = self._new_state_id()

            self._add_transition(start, child_frag.start_state, "ε")
            self._add_transition(child_frag.accept_state, child_frag.start_state, "ε")
            self._add_transition(child_frag.accept_state, accept, "ε")
            return _NFAFragment(start, accept)

        if node.type == RegexNodeType.QUESTION:
            start = self._new_state_id()
            child_frag = self._build_fragment(node.child)
            accept = self._new_state_id()

            self._add_transition(start, child_frag.start_state, "ε")
            self._add_transition(start, accept, "ε")
            self._add_transition(child_frag.accept_state, accept, "ε")
            return _NFAFragment(start, accept)

        raise ValueError(f"Unsupported RegexNodeType: {node.type}")
